services:
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    env_file:
      - ../apps/api/.env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      QDRANT_URL: http://qdrant:6333
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      COLLECTION: mcpx_docs
      PORT: 3001
    ports: ["3001:3001"]
    depends_on: [qdrant]

  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports: ["3000:3000"]
    depends_on: [api]

volumes:
  qdrant_data:
